# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 15 #todo: zero out

comments:
  UndocumentedPublicClass:
    active: false #todo: turned off as it's scanning generated code

formatting:
  Indentation:
    active: true
  CommentSpacing:
    active: false
  NoWildcardImports:
    active: false

style:
  ForbiddenComment:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false
